{{- if and .Values.radiusSecret.value (not .Values.radiusSecret.secretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aaa-radius-server.fullname" . }}-secret
  labels:
    {{- include "aaa-radius-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  radius-secret: {{ .Values.radiusSecret.value | quote }}
{{- end }}
