{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "subscriber-profile-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "subscriber-profile-api.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tls.secretName | default (printf "%s-tls" (include "subscriber-profile-api.fullname" .)) }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "subscriber-profile-api.fullname" . }}
                port:
                  name: http
{{- end }}
