apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "aaa-management-ui.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aaa-management-ui.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "aaa-management-ui.selectorLabels" . | nindent 6 }}
