apiVersion: v1
kind: Service
metadata:
  name: {{ include "aaa-lookup-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aaa-lookup-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "aaa-lookup-service.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
