{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aaa-regression-tester.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aaa-regression-tester.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "aaa-regression-tester.fullname" . }}-log-reader
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aaa-regression-tester.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "aaa-regression-tester.fullname" . }}-log-reader
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aaa-regression-tester.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "aaa-regression-tester.fullname" . }}-log-reader
subjects:
  - kind: ServiceAccount
    name: {{ include "aaa-regression-tester.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
